<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Surefire suite]" verbose="0">
  <test thread-count="5" name="Surefire test(failed)" verbose="0">
    <classes>
      <class name="SeliniumMaven.Tests.SubmitOrderTest">
        <methods>
          <include name="placeOrderTest" invocation-numbers="0 1"/>
          <include name="closeTheBrowser"/>
          <include name="launchApplication"/>
          <include name="CheckOrdersList"/>
        </methods>
      </class> <!-- SeliniumMaven.Tests.SubmitOrderTest -->
      <class name="SeliniumMaven.Tests.ErrorValidationsTest">
        <methods>
          <include name="loginErrorValidation"/>
          <include name="closeTheBrowser"/>
          <include name="launchApplication"/>
        </methods>
      </class> <!-- SeliniumMaven.Tests.ErrorValidationsTest -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
